- name: Install apache and php packages
  tags: apache, apache2, php, ubuntu, centos
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: CentOS - start and enable apache service
  tags: apache, httpd, centos
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: CentOS - change email address for admin
  tags: apache, httpd, centos
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin acke@acke.se
  when: ansible_distribution == "CentOS"
  notify: restart_apache

- name: Ubuntu, CentOS - copy default html file for site
  tags: apache, apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
