---

#The playbook for both Ubuntu and CentOS server
#----------------------------------------------
- hosts: all
  become: true
  tasks:



#  Ubuntu section
#  --------------
  - name: Ubuntu - Update cache & install apache and php packages
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


#  CentOS section
#  --------------
  - name: CentOS - Update cache & install apache and php packages
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
